name: Build and push Docker image to dockerhub

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      # Build date for image tags
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/vjumpkung-comfyui-api-serverless:latest
                    ${{ secrets.DOCKERHUB_USERNAME }}/vjumpkung-comfyui-api-serverless:${{ steps.date.outputs.date }}
